version: '3'
services:
  pebble:
    image: letsencrypt/pebble:v2.0.0
    environment:
       - PEBBLE_VA_SLEEPTIME=2
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver 10.30.50.3:8053
    ports:
      # HTTPS ACME API
      - 14000:14000
    networks:
      acmenet:
        ipv4_address: 10.30.50.2
  challtestsrv:
    image: letsencrypt/pebble-challtestsrv:v2.0.0
    command: pebble-challtestsrv -defaultIPv6 "" -defaultIPv4 10.30.50.3
    ports:
      - 8055:8055 # HTTP Management Interface
      - 8053:8053 # mock DNS server accessible via `dig @localhost -p 8053 +tcp ...`
    networks:
      acmenet:
        ipv4_address: 10.30.50.3

networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
